apiVersion: v1
kind: Service
metadata:
  labels:
    app: ticket-microservice
  name: ticket-microservice
  namespace: eventhub
spec:
  ports:
    - name: http
      port: 8085
      protocol: TCP
      targetPort: 8085
    - name: grpc
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    app: ticket-microservice
  type: ClusterIP
