services:
  gateway:
    build: .
    image: eventhub/gateway:v1
    container_name: eventhub-gateway
    ports:
      - "8082:8082"
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
