apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: eventhub
spec:
  type: NodePort
  selector:
    app: gateway-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30070
