apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
        - name: user-microservice
          image: utenti-service-user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
