apiVersion: v1
kind: Service
metadata:
  labels:
    app: event-microservice
  name: event-microservice
  namespace: eventhub
spec:
  ports:
    - name: 8083-8083
      nodePort: 30083
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: event-microservice
  type: NodePort
status:
  loadBalancer: {}
