services:
  agenda-service:
    build: .
    container_name: agenda-microservice
    ports:
      - "8084:8084"
    environment:
      - springdoc.api-docs.path=/v3/api-docs
      - springdoc.swagger-ui.path=/swagger-ui.html
      - springdoc.swagger-ui.disable-swagger-default-url=true
      - spring.datasource.url=jdbc:mariadb://mariadb:3307/agenda_db?useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=30000
      - spring.datasource.hikari.connection-timeout=30000
      - spring.datasource.hikari.maximum-pool-size=10
      - spring.datasource.hikari.minimum-idle=2
    networks:
      - agenda-network
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:10.11
    container_name: mariadb-agenda
    ports:
      - "3307:3307"
    environment:
      - MARIADB_DATABASE=agenda_db
      - MARIADB_USER=username
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=rootpassword
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - agenda-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$MARIADB_ROOT_PASSWORD",
          "--port=3307",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --port=3307

networks:
  agenda-network:
    name: agenda-network
    driver: bridge

volumes:
  mariadb-data:
