services:
  agenda-service:
    build: .
    container_name: agenda-microservice
    ports:
      - "8084:8084"
      - "9090:9090"
    environment:
      - springdoc.api-docs.path=/v3/api-docs
      - springdoc.swagger-ui.path=/swagger-ui.html
      - springdoc.swagger-ui.disable-swagger-default-url=true
      - springdoc.swagger-ui.server-url=http://localhost:8084
      - spring.data.mongodb.database=agenda_service
      - spring.data.mongodb.uri=mongodb://mongodb:27017/agenda_service
      - spring.profiles.active=docker
      - spring.rabbitmq.host=agenda-rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
    depends_on:
      - mongodb
      - agenda-rabbitmq
    networks:
      - agenda-network
      - rabbitmq-network

  mongodb:
    image: mongo:7.0
    container_name: agenda-mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=agenda_service
    volumes:
      - mongodb_data:/data/db
    networks:
      - agenda-network

  agenda-rabbitmq:
    image: rabbitmq:3-management
    container_name: agenda-rabbitmq
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - agenda-network
      - rabbitmq-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
  rabbitmq-data:
    name: rabbitmq-data

networks:
  agenda-network:
    name: agenda-network
    driver: bridge
  rabbitmq-network:
    name: rabbitmq-network
    driver: bridge
