services:
  user-service:
    build: .
    container_name: user-microservice
    ports:
      - "8080:8080"
    environment:
      - springdoc.api-docs.path=/v3/api-docs
      - springdoc.swagger-ui.path=/swagger-ui.html
      - springdoc.swagger-ui.disable-swagger-default-url=true
      - spring.datasource.url=jdbc:mariadb://mariadb:3306/utenti_db?useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=30000
      - spring.profiles.active=docker
    networks:
      - microservices-network
  mariadb:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    environment:
      - MARIADB_DATABASE=utenti_db
      - MARIADB_USER=username
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=rootpassword
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - microservices-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$MARIADB_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  microservices-network:
    driver: bridge

volumes:
  mariadb-data:
