services:
  user-service:
    build: .
    image: eventhub/user-microservice
    container_name: user-microservice
    ports:
      - "8080:8080"
    environment:
      - springdoc.api-docs.path=/v3/api-docs
      - springdoc.swagger-ui.path=/swagger-ui.html
      - springdoc.swagger-ui.disable-swagger-default-url=true
      - spring.datasource.url=jdbc:mariadb://mariadb:3306/utenti_db?useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=30000
      - spring.profiles.active=docker
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
    networks:
      - microservices-network
      - users-network
      - rabbitmq-network

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_DATABASE=utenti_db
      - MARIADB_USER=username
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=rootpassword
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - users-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - users-network
      - rabbitmq-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  users-network:
    name: users-network
    driver: bridge
  rabbitmq-network:
    name: rabbitmq-network
    driver: bridge
  microservices-network:
    external: true
    
volumes:
  mariadb-data:
  rabbitmq-data:
    name: rabbitmq-data