services:
  user-service:
    build: .
    container_name: user-microservice
    ports:
      - "8081:8080"
    environment:
      - springdoc.api-docs.path=/v1/api-docs
      - springdoc.swagger-ui.path=/swagger-ui/index.html
      - springdoc.swagger-ui.disable-swagger-default-url=true
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
