apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eventhub
  labels:
    app: event-microservice
  name: event-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-microservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: event-microservice
    spec:
      containers:
        - image: eventhub/event-microservice:latest
          name: event-microservice
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: event-microservice-config
