services:
  event-service:
    build: .
    container_name: event-microservice
    ports:
      - "8083:8083"
    environment:
      - springdoc.api-docs.path=/v3/api-docs
      - springdoc.swagger-ui.path=/swagger-ui.html
      - springdoc.swagger-ui.disable-swagger-default-url=true
      - springdoc.swagger-ui.server-url=http://localhost:8083
      - spring.data.mongodb.database=event_service
      - spring.data.mongodb.uri=mongodb://mongodb:27017/event_service
      - spring.profiles.active=docker
      - spring.rabbitmq.host=event-rabbitmq
      - spring.rabbitmq.port=5673
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
      - grpc.client.agenda-service.address=static://agenda-service:9090
    depends_on:
      - mongodb
      - event-rabbitmq
    networks:
      - event-network
      - rabbitmq-network

  mongodb:
    image: mongo:7.0
    container_name: event-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=event_service
    volumes:
      - mongodb_data:/data/db
    networks:
      - event-network

  event-rabbitmq:
    image: rabbitmq:3-management
    container_name: event-rabbitmq
    ports:
      - "5673:5673"
      - "15673:15673"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - event-network
      - rabbitmq-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
  rabbitmq-data:
    name: agenda-rabbitmq-data

networks:
  event-network:
    name: event-network
    driver: bridge
  rabbitmq-network:
    name: rabbitmq-network
    driver: bridge