services:
  event-service:
    build: .
    container_name: event-microservice
    ports:
      - "8083:8083"
    environment:
      - springdoc.api-docs.path=/v3/api-docs
      - springdoc.swagger-ui.path=/swagger-ui.html
      - springdoc.swagger-ui.disable-swagger-default-url=true
      - springdoc.swagger-ui.server-url=http://localhost:8083
      - spring.data.mongodb.database=event_service
      - spring.data.mongodb.uri=mongodb://event-mongodb:27017/event_service
      - grpc.client.agenda-service.address=static://agenda-service:9090
      - grpc.client.ticket-service.address=static://ticket-service:9091
    depends_on:
      - mongodb
    networks:
      - microservices-network
      - event-network

  mongodb:
    image: mongo:7.0
    container_name: event-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=event_service
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network
      - event-network

volumes:
  mongodb_data:

networks:
  event-network:
    name: event-network
    driver: bridge
  microservices-network:
    external: true
