apiVersion: v1
data:
  server.address: 0.0.0.0
  server.port: "8081"
  spring.application.name: mail_service
  springdoc.api-docs.path: /v3/api-docs
  springdoc.swagger-ui.path: /swagger-ui.html
  springdoc.swagger-ui.disable-swagger-default-url: "true"
  springdoc.swagger-ui.server-url: http://mail-microservice.eventhub.svc.cluster.local:8081
  spring.mail.host: smtp.gmail.com
  spring.mail.port: "587"
  spring.mail.protocol: smtp
  spring.mail.properties.mail.smtp.auth: "true"
  spring.mail.properties.mail.smtp.starttls.enable: "true"
  spring.mail.properties.mail.smtp.connectiontimeout: "5000"
  spring.mail.properties.mail.smtp.timeout: "5000"
  spring.mail.properties.mail.smtp.writetimeout: "5000"
  app.email.logo.path: static/images/logo-expanded.png
  spring.rabbitmq.host: rabbitmq
  spring.rabbitmq.password: guest
  spring.rabbitmq.port: "5672"
  spring.rabbitmq.username: guest
kind: ConfigMap
metadata:
  name: mail-microservice-config
  namespace: eventhub
