apiVersion: v1
kind: Service
metadata:
  labels:
    app: agenda-microservice
  name: agenda-microservice
  namespace: eventhub
spec:
  ports:
    - name: http
      port: 8084
      protocol: TCP
      targetPort: 8084
    - name: grpc
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: agenda-microservice
  type: ClusterIP
