apiVersion: v1
kind: Service
metadata:
  namespace: eventhub
  labels:
    app: event-microservice
  name: event-microservice
spec:
  ports:
    - name: 8083-8083
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: event-microservice
  type: ClusterIP
status:
  loadBalancer: {}
