apiVersion: v1
kind: Service
metadata:
  name: mail-microservice
  namespace: eventhub
  labels:
    app: mail-microservice
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: mail-microservice
