apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: eventhub
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: 5672-5672
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: 15672-15672
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq
  type: ClusterIP
status:
  loadBalancer: {}
