apiVersion: v1
kind: Service
metadata:
  namespace: eventhub
  labels:
    app: user-microservice
  name: user-microservice
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: user-microservice
  type: ClusterIP
status:
  loadBalancer: {}
